### ISSUE TITLE
error in imdlib respiratory

### ISSUE THREAD

**Issue by holeinsky** [iamsaswata/imdlib#14]
hello, i am doing a research on some Meteorological data but keep getting same error. 
"File "/home/vaibhav/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/imdlib/core.py", line 314, in open_data
    with open(fname, 'rb') as f:"

**Comment by iamsaswata** [comment]
Thanks for reaching out here. First of all, I hope you wanted to say "repository" and not "respiratory". Secondly, although you posted some part of the error message, I don't see the code that caused the error and produced the mentioned error message. However, still I beleive it's coming from the inappropriate setting of the  "file_dir" or in another word due to the the missing data records. You can check the [link](https://imdlib.readthedocs.io/en/latest/Usage.html#reading-imd-datasets), if you haven't done already.
