### ISSUE TITLE
to_csv add lat and lon if None is selected

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#3]
import imdlib as imd

start_yr =2018
end_yr = 2018
variable = 'rain' # other options are ('tmin'/ 'tmax')
data = imd.open_data((start_yr, end_yr), 'rain','yearwise') 
data.to_csv('test.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\imdlib\core.py", line 77, in to_csv
    self.lat_array, self.lon_array)
  File "C:\ProgramData\Miniconda3\lib\site-packages\imdlib\util.py", line 26, in get_lat_lon
    lat_index = np.abs(lat_rage - lat).argmin()
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by iamsaswata** [comment]
Thanks for reporting it. 
This was happening due to there was no support earlier for converting the entire 3D data array to 2D data format (with lat and lon as None). 

Now this is been fixed. We have added this feature with 11619a3476f2ae0474cbc62088455d9bfc6c0819. 
This modification is added at https://github.com/iamsaswata/imdlib/blob/master/imdlib/core.py#L94-L99

**Comment by pratiman-91** [comment]
Makes sense.
